name: Deploy to Vercel

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: team_tLkRiCytZyz6aMhuNcywRhWo
  VERCEL_PROJECT_ID: prj_RYicIYVMJCh3ikkZT3TbS9hf2z5h

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
